TEMPLATE = """
# coding=utf-8

#IMPORTS#


class #CLASS_NAME# (#PARENT#):
    def __init__(self#INIT_ARGS#):
        #LOCAL_OBJECTS#

#METHODS#

"""
PARENT = "#PARENT#"
LOCAL_OBJECTS = "#LOCAL_OBJECTS#"
IMPORTS = "#IMPORTS#"
CLASS_NAME = "#CLASS_NAME#"
INIT_ARGS = "#INIT_ARGS#"
METHODS = "#METHODS#"
